import { sql } from "drizzle-orm";
import {
  boolean,
  char,
  check,
  date,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

// Calendar dates are strings ('YYYY-MM-DD') so they never pass through a JS Date
// and can never shift a day with the process time zone.
const calendarDate = (name: string) => date(name, { mode: "string" });

// Instants are timestamptz; Date is the natural driver type for them.
const instant = (name: string) =>
  timestamp(name, { withTimezone: true, mode: "date" });

// Ids are generated by the application (no DB default) so a row's id is known before insert,
// for example to embed it in an alert payload or webhook body.
const id = () => uuid("id").primaryKey();

const createdAt = () => instant("created_at").notNull().default(sql`now()`);

// The database does not touch this on update; the application sets it on every update.
const updatedAt = () => instant("updated_at").notNull().default(sql`now()`);

export const blocks = pgTable(
  "blocks",
  {
    id: id(),
    name: text("name").notNull(),
    hotelName: text("hotel_name").notNull(),
    currency: char("currency", { length: 3 }).notNull(),
    startDate: calendarDate("start_date").notNull(),
    endDate: calendarDate("end_date").notNull(),
    cutoffDate: calendarDate("cutoff_date").notNull(),
    status: text("status").notNull(),
    basis: text("basis").notNull(),
    allowedAttritionBps: integer("allowed_attrition_bps").notNull(),
    damagesBps: integer("damages_bps").notNull(),
    taxBps: integer("tax_bps").notNull(),
    resellCredit: boolean("resell_credit").notNull(),
    minimumRounding: text("minimum_rounding").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    check("blocks_status_check", sql`${t.status} in ('active', 'closed')`),
    check("blocks_basis_check", sql`${t.basis} in ('cumulative', 'per_night')`),
    check(
      "blocks_minimum_rounding_check",
      sql`${t.minimumRounding} in ('ceil', 'floor', 'round')`,
    ),
    check(
      "blocks_allowed_attrition_bps_check",
      sql`${t.allowedAttritionBps} between 0 and 10000`,
    ),
    check("blocks_damages_bps_check", sql`${t.damagesBps} between 0 and 10000`),
    check("blocks_tax_bps_check", sql`${t.taxBps} between 0 and 5000`),
  ],
);

export const blockNights = pgTable(
  "block_nights",
  {
    blockId: uuid("block_id")
      .notNull()
      .references(() => blocks.id, { onDelete: "cascade" }),
    night: calendarDate("night").notNull(),
    contractedRooms: integer("contracted_rooms").notNull(),
    rateMinor: integer("rate_minor").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ name: "block_nights_pkey", columns: [t.blockId, t.night] }),
  ],
);

export const snapshots = pgTable(
  "snapshots",
  {
    id: id(),
    blockId: uuid("block_id")
      .notNull()
      .references(() => blocks.id, { onDelete: "cascade" }),
    asOfDate: calendarDate("as_of_date").notNull(),
    source: text("source").notNull(),
    note: text("note"),
    createdAt: createdAt(),
  },
  (t) => [
    unique("snapshots_block_id_as_of_date_unique").on(t.blockId, t.asOfDate),
    check(
      "snapshots_source_check",
      sql`${t.source} in ('manual', 'csv', 'api')`,
    ),
  ],
);

export const snapshotNights = pgTable(
  "snapshot_nights",
  {
    snapshotId: uuid("snapshot_id")
      .notNull()
      .references(() => snapshots.id, { onDelete: "cascade" }),
    night: calendarDate("night").notNull(),
    pickedUpRooms: integer("picked_up_rooms").notNull(),
    resoldRooms: integer("resold_rooms").notNull().default(0),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({
      name: "snapshot_nights_pkey",
      columns: [t.snapshotId, t.night],
    }),
  ],
);

export const evaluations = pgTable(
  "evaluations",
  {
    id: id(),
    blockId: uuid("block_id")
      .notNull()
      .references(() => blocks.id, { onDelete: "cascade" }),
    evaluatedFor: calendarDate("evaluated_for").notNull(),
    riskLevel: text("risk_level").notNull(),
    // The full Evaluation, validated by the Zod schema in packages/core, not by the database.
    result: jsonb("result").$type<Record<string, unknown>>().notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique("evaluations_block_id_evaluated_for_unique").on(
      t.blockId,
      t.evaluatedFor,
    ),
    check(
      "evaluations_risk_level_check",
      sql`${t.riskLevel} in ('met', 'on_track', 'at_risk', 'liable')`,
    ),
  ],
);

export const alertEvents = pgTable(
  "alert_events",
  {
    id: id(),
    blockId: uuid("block_id")
      .notNull()
      .references(() => blocks.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    // Together with (block_id, type) this makes alert insertion idempotent (on conflict do nothing).
    dedupeKey: text("dedupe_key").notNull(),
    payload: jsonb("payload").$type<Record<string, unknown>>().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique("alert_events_block_id_type_dedupe_key_unique").on(
      t.blockId,
      t.type,
      t.dedupeKey,
    ),
  ],
);

export const webhookEndpoints = pgTable("webhook_endpoints", {
  id: id(),
  url: text("url").notNull(),
  secret: text("secret").notNull(),
  active: boolean("active").notNull().default(true),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const webhookDeliveries = pgTable(
  "webhook_deliveries",
  {
    id: id(),
    endpointId: uuid("endpoint_id")
      .notNull()
      .references(() => webhookEndpoints.id, { onDelete: "cascade" }),
    // Nullable because PING test deliveries have no alert event.
    alertEventId: uuid("alert_event_id").references(() => alertEvents.id, {
      onDelete: "cascade",
    }),
    eventType: text("event_type").notNull(),
    body: jsonb("body").$type<Record<string, unknown>>().notNull(),
    status: text("status").notNull(),
    attempts: integer("attempts").notNull().default(0),
    nextAttemptAt: instant("next_attempt_at").notNull(),
    lastStatusCode: integer("last_status_code"),
    lastError: text("last_error"),
    deliveredAt: instant("delivered_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    // Serves the worker's poll for due pending deliveries.
    index("webhook_deliveries_status_next_attempt_at_idx").on(
      t.status,
      t.nextAttemptAt,
    ),
    check(
      "webhook_deliveries_status_check",
      sql`${t.status} in ('pending', 'delivered', 'failed')`,
    ),
  ],
);

export type BlockRow = typeof blocks.$inferSelect;
export type BlockNightRow = typeof blockNights.$inferSelect;
export type SnapshotRow = typeof snapshots.$inferSelect;
export type SnapshotNightRow = typeof snapshotNights.$inferSelect;
export type EvaluationRow = typeof evaluations.$inferSelect;
export type AlertEventRow = typeof alertEvents.$inferSelect;
export type WebhookEndpointRow = typeof webhookEndpoints.$inferSelect;
export type WebhookDeliveryRow = typeof webhookDeliveries.$inferSelect;
